// Code generated by "stringer -type=OpCode"; DO NOT EDIT.

package opcodes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Add-100]
	_ = x[Sub-101]
	_ = x[Mul-102]
	_ = x[Div-103]
	_ = x[Rem-104]
	_ = x[Xor-105]
	_ = x[Not-106]
	_ = x[Or-107]
	_ = x[Neg-108]
	_ = x[Br-200]
	_ = x[Be-201]
	_ = x[Bne-202]
	_ = x[Blt-203]
	_ = x[Bgt-204]
	_ = x[Bt-205]
	_ = x[Bf-206]
	_ = x[Cmp-300]
	_ = x[Clt-301]
	_ = x[Cgt-302]
	_ = x[Cle-303]
	_ = x[Cge-304]
	_ = x[Ldc8-400]
	_ = x[Pop-401]
	_ = x[Dup-402]
	_ = x[LdLoc-403]
	_ = x[StLoc-404]
	_ = x[LdStr-405]
	_ = x[Nop-500]
	_ = x[Ret-501]
	_ = x[Call-502]
}

const (
	_OpCode_name_0 = "AddSubMulDivRemXorNotOrNeg"
	_OpCode_name_1 = "BrBeBneBltBgtBtBf"
	_OpCode_name_2 = "CmpCltCgtCleCge"
	_OpCode_name_3 = "Ldc8PopDupLdLocStLocLdStr"
	_OpCode_name_4 = "NopRetCall"
)

var (
	_OpCode_index_0 = [...]uint8{0, 3, 6, 9, 12, 15, 18, 21, 23, 26}
	_OpCode_index_1 = [...]uint8{0, 2, 4, 7, 10, 13, 15, 17}
	_OpCode_index_2 = [...]uint8{0, 3, 6, 9, 12, 15}
	_OpCode_index_3 = [...]uint8{0, 4, 7, 10, 15, 20, 25}
	_OpCode_index_4 = [...]uint8{0, 3, 6, 10}
)

func (i OpCode) String() string {
	switch {
	case 100 <= i && i <= 108:
		i -= 100
		return _OpCode_name_0[_OpCode_index_0[i]:_OpCode_index_0[i+1]]
	case 200 <= i && i <= 206:
		i -= 200
		return _OpCode_name_1[_OpCode_index_1[i]:_OpCode_index_1[i+1]]
	case 300 <= i && i <= 304:
		i -= 300
		return _OpCode_name_2[_OpCode_index_2[i]:_OpCode_index_2[i+1]]
	case 400 <= i && i <= 405:
		i -= 400
		return _OpCode_name_3[_OpCode_index_3[i]:_OpCode_index_3[i+1]]
	case 500 <= i && i <= 502:
		i -= 500
		return _OpCode_name_4[_OpCode_index_4[i]:_OpCode_index_4[i+1]]
	default:
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
